/// The goal of this file is, if the impact.moe API doesn't work, to have some data, to allow you, user, to experiment the app
/// even if it without all the recent data.

dynamic characterjson = [
  {
    "id": "albedo",
    "name": "Albedo",
    "tier": "A",
    "rarity": 5,
    "weapon": "Sword",
    "element": "Geo",
    "description":
        "An alchemist based in Mondstadt, in the service of the Knights of Favonius.",
    "region": "Mondstadt",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Albedo.webp",
    "quote": "https://impact.moe/assets/img/quotes/albedo.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Albedo.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/albedo.webp",
    "title": "Kreideprinz",
    "birthday": "September 13th",
    "constellation": "Princeps Cretaceus",
    "chineseVA": "Minyue Lu (陆敏悦), aka \"Mace",
    "japaneseVA": "Kenji Nojima (野島健児)",
    "englishVA": "Khoi Dao",
    "koreanVA": "Kim Myungjun (김명준)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "aloy",
    "name": "Aloy",
    "tier": "",
    "rarity": 5,
    "weapon": "Bow",
    "element": "Cryo",
    "description":
        "An agile hunter from the Nora tride. With bow in hand, she's always ready to protect the innocent.",
    "region": "Horizon Zero Dawn",
    "faction": "Wandering Heroine",
    "image": "https://impact.moe/assets/img/portraits/Aloy.webp",
    "quote": "https://impact.moe/assets/img/quotes/aloy.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Aloy.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/aloy.webp",
    "title": "Savior From Another World",
    "birthday": "April 4th",
    "constellation": "Nora Fortis",
    "chineseVA": "Mufei (沐霏)",
    "japaneseVA": "Ayahi Takagaki (高垣 彩陽)",
    "englishVA": "Ashly Burch",
    "koreanVA": "Jo Hyeon-jeong (조현정)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "amber",
    "name": "Amber",
    "tier": "D",
    "rarity": 4,
    "weapon": "Bow",
    "element": "Pyro",
    "description":
        "A perky, straightforward girl, who is also the only Outrider of the Knights of Favonius. Her amazing mastery of the glider has made her a three-time winner of the Gliding Championship in Mondstadt. As a rising star within the Knights of Favonius, Amber is always ready for any challenging tasks.",
    "region": "Mondstadt",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Amber.webp",
    "quote": "https://impact.moe/assets/img/quotes/amber.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Amber.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/amber.webp",
    "title": "Outrider",
    "birthday": "August 10th",
    "constellation": "Lepus",
    "chineseVA": "Tingting Hu (胡婷婷), aka \"Niunai Jun\" (牛奶君) lit: Milk-kun",
    "japaneseVA": "Manaka Iwami (石見 舞菜香)",
    "englishVA": "Kelly Baskin",
    "koreanVA": "Kim Yeon-woo (김연우)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "ayaka",
    "name": "Kamisato Ayaka",
    "tier": "S",
    "rarity": 5,
    "weapon": "Sword",
    "element": "Cryo",
    "description":
        "The princess of the House Kamisato of Inazuma. She is the embodiment of nobility and elegance.",
    "region": "Inazuma",
    "faction": "Yashiro Commission",
    "image": "https://impact.moe/assets/img/portraits/Ayaka.webp",
    "quote": "https://impact.moe/assets/img/quotes/ayaka.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Ayaka.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/ayaka.webp",
    "title": "Frostflake Heron",
    "birthday": "September 28th",
    "constellation": "Grus Nivis",
    "chineseVA": "Xiao N (小N)",
    "japaneseVA": "Saori Hayami (早見沙織)",
    "englishVA": "Erica Mendez",
    "koreanVA": "Lee Yu-ri (이유리)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "barbara",
    "name": "Barbara",
    "tier": "A",
    "rarity": 4,
    "weapon": "Catalyst",
    "element": "Hydro",
    "description":
        "The Deaconess of the Favonius Church and a shining starlet adored by all. Although the concept of a starlet is rather novel in a city of bards, the people of Mondstadt love Barbara nonetheless. \"I owe everything to the city's spirit of freedom\" — Barbara, regarding her popularity.",
    "region": "Mondstadt",
    "faction": "Church of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Barbara.webp",
    "quote": "https://impact.moe/assets/img/quotes/barbara.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Barbara.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/barbara.webp",
    "title": "Shining Idol",
    "birthday": "July 5th",
    "constellation": "Crater",
    "chineseVA": "Yuanyuan Song (宋媛媛)",
    "japaneseVA": "Akari Kitō (鬼頭 明里)",
    "englishVA": "Laura Stahl",
    "koreanVA": "Yun AhYeong (윤아영)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "beidou",
    "name": "Beidou",
    "tier": "B",
    "rarity": 4,
    "weapon": "Claymore",
    "element": "Electro",
    "description":
        "Captain of the Crux, with quite the reputation in Liyue. There are those who say she can split mountains and part the sea. Others say she draws lightning through her sword. Some say that even the mightiest of sea beasts are no match for her. For those not from Liyue, it may sound like a hearty joke, but those that have sailed with her will say- \"No matter what sea beasts there may be, Beidou will be sure to split them all in two.",
    "region": "Liyue",
    "faction": "Crux Fleet",
    "image": "https://impact.moe/assets/img/portraits/Beidou.webp",
    "quote": "https://impact.moe/assets/img/quotes/beidou.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Beidou.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/beidou.webp",
    "title": "Uncrowned Lord of the Ocean",
    "birthday": "February 14th",
    "constellation": "Victor Mare",
    "chineseVA": "Yajing Tang (唐雅菁)",
    "japaneseVA": "Ami Koshimizu (小清水 亜美)",
    "englishVA": "Allegra Clark",
    "koreanVA": "Jeong Yoo-Mi (정유미)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "bennett",
    "name": "Bennett",
    "tier": "S",
    "rarity": 4,
    "weapon": "Sword",
    "element": "Pyro",
    "description":
        "The few young adventurers that the Mondstadt Adventurers' Guild has always find themselves tangled up in baffling bouts of bad luck. He is the only active member of his own adventure group, known as \"Benny's Adventure Team,\" after all the other members decided to \"take leave\" following a series of unfortunate incidents. As a result, the team is currently on the verge of being dissolved. Being unable to break the poor boy's heart, Katheryne of the Adventurers' Guild has kept \"Benny's Adventure Team\" on the books, whilst also hiding from him the fact that all the other members have long since officially left the team.",
    "region": "Mondstadt",
    "faction": "Adventurers' Guild",
    "image": "https://impact.moe/assets/img/portraits/Bennett.webp",
    "quote": "https://impact.moe/assets/img/quotes/bennett.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Bennett.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/bennett.webp",
    "title": "Trial by Fire",
    "birthday": "February 29th",
    "constellation": "Rota Calamitas",
    "chineseVA": "Xueting Mu (穆雪婷)",
    "japaneseVA": "Ryota Osaka (逢坂 良太)",
    "englishVA": "Cristina Vee Valenzuela",
    "koreanVA": "Song HaRim(송하림)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "chongyun",
    "name": "Chongyun",
    "tier": "B",
    "rarity": 4,
    "weapon": "Claymore",
    "element": "Cryo",
    "description":
        "An exorcist who roams the land with Liyue as his base of operations, evil spirits fleeing wherever he goes. As the heir to a clan of exorcists, he has always possessed abilities superior to most. However, these abilities are not the result of training, but of an inborn trait - congenital positivity",
    "region": "Liyue",
    "faction": "",
    "image": "https://impact.moe/assets/img/portraits/Chongyun.webp",
    "quote": "https://impact.moe/assets/img/quotes/chongyun.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Chongyun.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/chongyun.webp",
    "title": "Frozen Ardur",
    "birthday": "September 7th",
    "constellation": "Nubis Caesor",
    "chineseVA": "Jinchuan (金船)",
    "japaneseVA": "Soma Saito (斉藤 壮馬)",
    "englishVA": "Beau Bridgland",
    "koreanVA": "Yang JeongHwa (양정화)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "dainsleif",
    "name": "Dainsleif",
    "tier": "",
    "rarity": 0,
    "weapon": "sword",
    "element": "NULL",
    "description":
        "Dainsleif is a man of mysterious origins, but claims to have knowledge of fate itself. Previously known as the \"Twilight Sword\", he was one of the royal guards of the final dynasty of Khaenri'ah.",
    "region": "Khaenri'ah",
    "faction": "",
    "image": "https://impact.moe/assets/img/portraits/Dainsleif.webp",
    "quote": "",
    "icon": "",
    "squareCard": "https://impact.moe/assets/img/square-cards/dainsleif.webp",
    "title": "Bough Keeper",
    "birthday": "",
    "constellation": "",
    "chineseVA": "Ye Sun (孙晔)",
    "japaneseVA": "Kenjiro Tsuda (津田 健次郎)",
    "englishVA": "Yuri Lowenthal",
    "koreanVA": "Choi Han (최한)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "diluc",
    "name": "Diluc",
    "tier": "S",
    "rarity": 5,
    "weapon": "Claymore",
    "element": "Pyro",
    "description":
        "As the wealthiest gentleman in Mondstadt, the ever-dapper Diluc always presents himself as the epitome of perfection. But behind the courteous visage burns a zealous soul that has sworn to protect Mondstadt at all costs, allowing him to mercilessly vanquish all who threaten his city.",
    "region": "Mondstadt",
    "faction": "Dawn Winery",
    "image": "https://impact.moe/assets/img/portraits/Diluc.webp",
    "quote": "https://impact.moe/assets/img/quotes/diluc.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Diluc.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/diluc.webp",
    "title": "Darknight Hero",
    "birthday": "April 30th",
    "constellation": "Noctua",
    "chineseVA": "Yang Ma (马洋)",
    "japaneseVA": "Kensho Ono (小野 賢章)",
    "englishVA": "Sean Chiplock",
    "koreanVA": "Choi SeungHoon (최승훈)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "diona",
    "name": "Diona",
    "tier": "B",
    "rarity": 4,
    "weapon": "Bow",
    "element": "Cryo",
    "description":
        "A young lady who has inherited trace amounts of non-human blood. She is the incredible popular bartender of the Cat's Tail tavern.",
    "region": "Mondstadt",
    "faction": "Cat's Tail Tavern",
    "image": "https://impact.moe/assets/img/portraits/Diona.webp",
    "quote": "https://impact.moe/assets/img/quotes/diona.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Diona.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/diona.webp",
    "title": "Kätzlein Cocktail",
    "birthday": "January 18th",
    "constellation": "Feles",
    "chineseVA": "Ya Nuo (诺亚)",
    "japaneseVA": "Shiori Izawa (井澤 詩織)",
    "englishVA": "Dina Sherman",
    "koreanVA": "Woo Jeong-shin (우정신)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "eula",
    "name": "Eula",
    "tier": "S",
    "rarity": 5,
    "weapon": "Claymore",
    "element": "Cryo",
    "description":
        "The Spindrift Knight, a scion of the old aristocracy, and the Captain of the Knights of Favonius Reconnaissance Company. The reason for which a descendant of the ancient nobles might join the Knights remains a great mystery in Mondstadt to this very day.",
    "region": "Mondstadt",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Eula.webp",
    "quote": "https://impact.moe/assets/img/quotes/eula.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Eula.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/eula.webp",
    "title": "Dance of the Shimmering Wave",
    "birthday": "October 25th",
    "constellation": "Aphros Delos",
    "chineseVA": "Ziyin (子音)",
    "japaneseVA": "Rina Sato (佐藤利奈)",
    "englishVA": "Suzie Yeung",
    "koreanVA": "Kim Hyeon-ji (김현지)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "fischl",
    "name": "Fischl",
    "tier": "A",
    "rarity": 4,
    "weapon": "Bow",
    "element": "Electro",
    "description":
        "A mysterious girl who calls herself \"Prinzessin der Verurteilung\" and travels with a night raven named Oz. Currently serves as an investigator in the Adventurers' Guild. Through her unique abilities, eccentric character, and (while she would never admit it herself) hard work, Fischl has become a rising star among the Adventurers' Guild's investigators, earning the recognition of all.",
    "region": "Mondstadt",
    "faction": "Adventurers' Guild",
    "image": "https://impact.moe/assets/img/portraits/Fischl.webp",
    "quote": "https://impact.moe/assets/img/quotes/fischl.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Fischl.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/fischl.webp",
    "title": "Sovereign of Immernachtreich",
    "birthday": "May 27th",
    "constellation": "Corvus",
    "chineseVA": "Minyue Lu (陆敏悦), aka \"Mace\" Oz: Yuantao Li (李元韬)",
    "japaneseVA": "Maaya Uchida (内田 真礼) Oz: Yasunori Masutani (増谷 康紀)",
    "englishVA": "Brittany Cox Oz: Ben Pronsky",
    "koreanVA": "Park GoWoon (박고운) Oz: Lee Hyun (이현)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "ganyu",
    "name": "Ganyu",
    "tier": "S",
    "rarity": 5,
    "weapon": "Bow",
    "element": "Cryo",
    "description":
        "The secretary to the Liyue Qixing. The blood of both human and illuminated beast flows within her veins.",
    "region": "Liyue",
    "faction": "Yuehai Pavilion",
    "image": "https://impact.moe/assets/img/portraits/Ganyu.webp",
    "quote": "https://impact.moe/assets/img/quotes/ganyu.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Ganyu.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/ganyu.webp",
    "title": "Plenilune Gaze",
    "birthday": "December 2nd",
    "constellation": "Sinae Unicornis",
    "chineseVA": "Su Lin (林簌)",
    "japaneseVA": "Reina Ueda (上田 麗奈)",
    "englishVA": "Jennifer Losi",
    "koreanVA": "Kim Seonhye (김선혜)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "gorou",
    "name": "Gorou",
    "tier": "",
    "rarity": 4,
    "weapon": "Bow",
    "element": "Geo",
    "description":
        "The great general of Watatsumi Island's forces. He has gained respect and prestige, but always shows himself to be a humble leader. He is deeply trusted by his subordinates and is someone with whom you can share your feelings without shame.",
    "region": "Inazuma",
    "faction": "Watatsumi Army",
    "image": "https://impact.moe/assets/img/portraits/Gorou.webp",
    "quote": "https://impact.moe/assets/img/quotes/gorou.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Gorou.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/gorou.webp",
    "title": "General of the Watatsumi Army",
    "birthday": "May 18th",
    "constellation": "Canis Bellatoris",
    "chineseVA": "Yang Xinran (杨昕燃)",
    "japaneseVA": "Tasuku Hatanaka (畠中 祐)",
    "englishVA": "Cory Yee",
    "koreanVA": "Lee Sae-byeok (이새벽)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "hu-tao",
    "name": "Hu Tao",
    "tier": "S",
    "rarity": 5,
    "weapon": "Polearm",
    "element": "Pyro",
    "description":
        "Hu Tao is the 77th Director of the Wangsheng Funeral Parlor, a person vital to managing Liyue's funerary affairs.",
    "region": "Liyue",
    "faction": "Wangsheng Funeral Parlor",
    "image": "https://impact.moe/assets/img/portraits/Hu-Tao.webp",
    "quote": "https://impact.moe/assets/img/quotes/hu-tao.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Hu-Tao.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/hu-tao.webp",
    "title": "Fragrance in Thaw",
    "birthday": "July 15th",
    "constellation": "Papilio Charontis",
    "chineseVA": "Dian Tao (陶典)",
    "japaneseVA": "Rie Takahashi (高橋李依)",
    "englishVA": "Brianna Knickerbocker",
    "koreanVA": "Kim Ha-Ru (김하루)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "itto",
    "name": "Arataki Itto",
    "tier": "",
    "rarity": 5,
    "weapon": "Claymore",
    "element": "Geo",
    "description":
        "Descendant of the oni, of intrepid spirit and noble heart. Fast as the wind and mighty as thunder.",
    "region": "Inazuma",
    "faction": "Arataki Gang",
    "image": "https://impact.moe/assets/img/portraits/Itto.webp",
    "quote": "https://impact.moe/assets/img/quotes/itto.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Itto.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/itto.webp",
    "title": "The First and Greatest Head of the Arataki Gang",
    "birthday": "June 1st",
    "constellation": "Taurus Iracundus",
    "chineseVA": "Zhaokun Liu (刘照坤)",
    "japaneseVA": "Takanori Nishikawa (西川貴教)",
    "englishVA": "Max Mittelman",
    "koreanVA": "Song Joon-seok (송준석)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "jean",
    "name": "Jean",
    "tier": "A",
    "rarity": 5,
    "weapon": "Sword",
    "element": "Anemo",
    "description":
        "As the Acting Grandmaster of the Knights, Jean has always been devoted to her duties and maintaining peace in Mondstadt. She had taken precautions long before the onset of Stormterror's assault, and she will guard Mondstadt with her life as always.",
    "region": "Mondstadt",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Jean.webp",
    "quote": "https://impact.moe/assets/img/quotes/jean.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Jean.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/jean.webp",
    "title": "Acting Grandmaster",
    "birthday": "March 14th",
    "constellation": "Leo Minor",
    "chineseVA": "Su Lin (林簌)",
    "japaneseVA": "Chiwa Saitō (斎藤 千和)",
    "englishVA": "Stephanie Southerland",
    "koreanVA": "Yeong-mi Ahn (안영미)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "kaeya",
    "name": "Kaeya",
    "tier": "C",
    "rarity": 4,
    "weapon": "Sword",
    "element": "Cryo",
    "description":
        "In the Knights of Favonius, Kaeya is the most trusted aide for the Acting Grand Master Jean. You can always count on him to solve any intractable problems. Everyone in Mondstadt loves Kaeya, but no one knows what secrets this witty, charming knight has..",
    "region": "Mondstadt",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Kaeya.webp",
    "quote": "https://impact.moe/assets/img/quotes/kaeya.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Kaeya.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/kaeya.webp",
    "title": "Cavalry Captain",
    "birthday": "November 30th",
    "constellation": "Pavo Ocellus",
    "chineseVA": "Ye Sun (孙晔)",
    "japaneseVA": "Kohsuke Toriumi (鳥海 浩輔)",
    "englishVA": "Josey Montana McCoy",
    "koreanVA": "Jeong JuWon (정주원)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "kazuha",
    "name": "Kaedehara Kazuha",
    "tier": "S",
    "rarity": 5,
    "weapon": "Sword",
    "element": "Anemo",
    "description":
        "A wandering samurai from Inazuma with a modest and gentle personality. Beneath a youthful and carefree demeanor lies a heart that hides a great many burdens from the past. Seemingly easygoing, Kazuha has his own code of conduct.",
    "region": "Inazuma",
    "faction": "Crux Fleet",
    "image": "https://impact.moe/assets/img/portraits/Kazuha.webp",
    "quote": "https://impact.moe/assets/img/quotes/kazuha.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Kazuha.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/kazuha.webp",
    "title": "Scarlet Leaves Pursue Wild Waves",
    "birthday": "October 29",
    "constellation": "Acer Palmatum",
    "chineseVA": "Banma (斑马)",
    "japaneseVA": "Shimazaki Nobunaga (岛崎信长)",
    "englishVA": "Mark Whitten",
    "koreanVA": "Kim Shin-woo (김신우)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "keqing",
    "name": "Keqing",
    "tier": "A",
    "rarity": 5,
    "weapon": "Sword",
    "element": "Electro",
    "description":
        "The Yuheng of the Liyue Qixing. Keqing has much to say about Rex Lapis' unilateral approach to policymaking in Liyue ⁠— but in truth, gods admire skeptics such as her quite a lot.",
    "region": "Liyue",
    "faction": "Liyue Qixing",
    "image": "https://impact.moe/assets/img/portraits/Keqing.webp",
    "quote": "https://impact.moe/assets/img/quotes/keqing.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Keqing.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/keqing.webp",
    "title": "Driving Thunder",
    "birthday": "November 20th",
    "constellation": "Trulla Cementarii",
    "chineseVA": "Ying Xie (谢莹)",
    "japaneseVA": "Eri Kitamura (喜多村 英梨)",
    "englishVA": "Kayli Mills",
    "koreanVA": "Bohee Lee (이보희)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "klee",
    "name": "Klee",
    "tier": "S",
    "rarity": 5,
    "weapon": "Catalyst",
    "element": "Pyro",
    "description":
        "An explosives expert and a regular at the Knights of Favonius' confinement room. Also known as Fleeing Sunlight.",
    "region": "Mondstadt",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Klee.webp",
    "quote": "https://impact.moe/assets/img/quotes/klee.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Klee.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/klee.webp",
    "title": "Fleeing Sunlight",
    "birthday": "July 27th",
    "constellation": "Trifolium",
    "chineseVA": "Ling Hua (花玲)",
    "japaneseVA": "Misaki Kuno (久野 美咲)",
    "englishVA": "Poonam Basu",
    "koreanVA": "Bang Yeonji (방연지)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "kokomi",
    "name": "Sangonomiya Kokomi",
    "tier": "",
    "rarity": 5,
    "weapon": "Catalyst",
    "element": "Hydro",
    "description":
        "Kokomi is the Divine Priestess of Watatsumi Island, and also serves as its supreme leader. She is well-versed in the art of war, is good at strategizing and has keen insights into military affairs. She is also adept at handling domestic affairs, diplomacy, and other matters. Still, this unfathomable leader has a mysterious side to her...",
    "region": "Inazuma",
    "faction": "Watatsumi Island",
    "image": "https://impact.moe/assets/img/portraits/Kokomi.webp",
    "quote": "https://impact.moe/assets/img/quotes/kokomi.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Kokomi.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/kokomi.webp",
    "title": "Pearl of Wisdom",
    "birthday": "February 22nd",
    "constellation": "Dracaena Somnolenta",
    "chineseVA": "Guiniang (龟娘)",
    "japaneseVA": "Suzuko Mimori (三森すずこ)",
    "englishVA": "Risa Mei",
    "koreanVA": "Yeo Yun-mi (여윤미)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "lisa",
    "name": "Lisa",
    "tier": "C",
    "rarity": 4,
    "weapon": "Catalyst",
    "element": "Electro",
    "description":
        "The librarian of the Knights of Favonius. In addition to her elegance and charm, Lisa is also highly educated. She is said to have been the most talented sorceress to study at the Sumeru Academia in the last two centuries. It is known that Lisa chose to return to Mondstadt after two years of advanced study in Sumeru, but the reason for the decision is not. Lisa currently serves as a librarian in the Knights of Favonius. She is an intellectual witch who can never get enough naps. As the Librarian of the Knights of Favonius, Lisa is smart in that she always knows exactly what to do with whatever troubles her. As much as she loves her sleep, she still manages to keep everything under control in a calm, composed manner.",
    "region": "Mondstadt",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Lisa.webp",
    "quote": "https://impact.moe/assets/img/quotes/lisa.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Lisa.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/lisa.webp",
    "title": "Witch of Purple Rose",
    "birthday": "June 9th",
    "constellation": "Tempus Fugit",
    "chineseVA": "Ke Zhong (钟可)",
    "japaneseVA": "Rie Tanaka (田中 理恵)",
    "englishVA": "Mara Junot",
    "koreanVA": "Park GoWoon (박고운)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "miko",
    "name": "Yae Miko",
    "tier": "",
    "rarity": 5,
    "weapon": "Catalyst",
    "element": "Electro",
    "description":
        "The head shrine maiden in charge of Grand Narukami Shrine and a descendant of Kitsune lineage, Eternity's servant and friend, and the intimidating editor-in-chief of Yae Publishing House, a publisher of light novels...\nThe enigmatic Guuji, with many identities, may never be fully understood by mortals for what she truly is in her heart of hearts.",
    "region": "Inazuma",
    "faction": "Grand Narukami Shrine",
    "image": "https://impact.moe/assets/img/portraits/Miko.webp",
    "quote": "https://impact.moe/assets/img/quotes/miko.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Miko.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/miko.webp",
    "title": "Guuji of the Grand Narukami Shrine",
    "birthday": "June 27th",
    "constellation": "Divina Vulpes",
    "chineseVA": "Mingya Du (杜冥鸦)",
    "japaneseVA": "Ayane Sakura (佐倉綾音)",
    "englishVA": "Ratana",
    "koreanVA": "Moon Yoo-jeong (문유정)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "mimi",
    "name": "Mimi",
    "tier": "",
    "rarity": 0,
    "weapon": "catalyst",
    "element": "hydro",
    "description": "",
    "region": "Inazuma",
    "faction": "",
    "image": "",
    "quote": "",
    "icon": "",
    "squareCard": "",
    "title": "",
    "birthday": "",
    "constellation": "",
    "chineseVA": "",
    "japaneseVA": "",
    "englishVA": "",
    "koreanVA": "",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "mona",
    "name": "Mona",
    "tier": "A",
    "rarity": 5,
    "weapon": "Catalyst",
    "element": "Hydro",
    "description":
        "A mysterious young astrologer who proclaims herself to be \"Astrologist Mona Megistus,\" and who possesses abilities to match the title. Erudite, but prideful.",
    "region": "Mondstadt",
    "faction": "Hexenzirkel",
    "image": "https://impact.moe/assets/img/portraits/Mona.webp",
    "quote": "https://impact.moe/assets/img/quotes/mona.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Mona.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/mona.webp",
    "title": "Enigmatic Astrologer",
    "birthday": "August 31st",
    "constellation": "Astrolabos",
    "chineseVA": "Tingting Chen (陈婷婷)",
    "japaneseVA": "Konomi Kohara (小原 好美)",
    "englishVA": "Felecia Angelle",
    "koreanVA": "Woo Jeong-shin (우정신)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "ningguang",
    "name": "Ningguang",
    "tier": "B",
    "rarity": 4,
    "weapon": "Catalyst",
    "element": "Geo",
    "description":
        "Owner of the Jade Chamber in the skies above Liyue, there are stories abound about Ningguang, with her elegance and mysterious smile. As a Tianquan of the Liyue Qixing, not only does she embody law and order, she also represents fortune and wit.",
    "region": "Liyue",
    "faction": "Liyue Qixing",
    "image": "https://impact.moe/assets/img/portraits/Ningguang.webp",
    "quote": "https://impact.moe/assets/img/quotes/ningguang.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Ningguang.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/ningguang.webp",
    "title": "Eclipsing Star",
    "birthday": "August 26th",
    "constellation": "Opus Aequilibrium",
    "chineseVA": "Mingya Du (杜冥鸦)",
    "japaneseVA": "Sayaka Ohara (大原 さやか)",
    "englishVA": "Erin Ebers",
    "koreanVA": "Kwak Kyumi (곽규미)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "noelle",
    "name": "Noelle",
    "tier": "C",
    "rarity": 4,
    "weapon": "Claymore",
    "element": "Geo",
    "description":
        "Like most of Mondstadt's young people, Noelle always dreamed of being a knight of Favonius when she grew up. She may not have what it takes to be a knight just yet, but she is learning. Working as a maid at the Knights' headquarters, she is constantly taking notes on what constitutes knightly speech, knightly conduct, and knightly customs. She holds firm to her belief that one day she will join their ranks - she just needs to keep trying her hardest at everything she does.",
    "region": "Mondstadt",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Noelle.webp",
    "quote": "https://impact.moe/assets/img/quotes/noelle.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Noelle.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/noelle.webp",
    "title": "Maid of Favonius",
    "birthday": "March 21st",
    "constellation": "Parma Cordis",
    "chineseVA": "Ning Yan (宴宁)",
    "japaneseVA": "Kanon Takao (高尾 奏音)",
    "englishVA": "Laura Faye Smith",
    "koreanVA": "Bohee Lee (이보희)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "qiqi",
    "name": "Qiqi",
    "tier": "S",
    "rarity": 5,
    "weapon": "Sword",
    "element": "Cryo",
    "description":
        "An apprentice and herb gatherer at Bubu Pharmacy. \"Blessed\" by the adepti with a body that cannot die, this petite zombie cannot do anything without first giving herself orders to do it. Qiqi's memory is like a sieve. Out of necessity, she always carries around a notebook in which she writes anything important that she is sure to forget later.",
    "region": "Liyue",
    "faction": "Bubu Pharmacy",
    "image": "https://impact.moe/assets/img/portraits/Qiqi.webp",
    "quote": "https://impact.moe/assets/img/quotes/qiqi.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Qiqi.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/qiqi.webp",
    "title": "Pharmacist",
    "birthday": "March 3rd",
    "constellation": "Pristina Nola",
    "chineseVA": "Ning Yan (宴宁)",
    "japaneseVA": "Yukari Tamura (田村 ゆかり)",
    "englishVA": "Christie Cate",
    "koreanVA": "Seul Lee (이슬)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "razor",
    "name": "Razor",
    "tier": "A",
    "rarity": 4,
    "weapon": "Claymore",
    "element": "Electro",
    "description":
        "Some say he is an orphan raised by wolves. Others say he is a wolf spirit in human form. He is most at home in the wild, fighting with claw and thunder. To this day the wolf boy can be found prowling the forest, where he and his wolf pack hunt to survive using nothing more than their animal instincts.",
    "region": "Mondstadt",
    "faction": "Wolvendom",
    "image": "https://impact.moe/assets/img/portraits/Razor.webp",
    "quote": "https://impact.moe/assets/img/quotes/razor.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Razor.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/razor.webp",
    "title": "Wolf Boy",
    "birthday": "September 9th",
    "constellation": "Lupus Minor",
    "chineseVA": "Shuai Zhou (周帅)",
    "japaneseVA": "Koki Uchiyama (内山 昂輝)",
    "englishVA": "Todd Haberkorn",
    "koreanVA": "Seo-yeong Kim (김서영)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "rosaria",
    "name": "Rosaria",
    "tier": "B",
    "rarity": 4,
    "weapon": "Polearm",
    "element": "Cryo",
    "description":
        "Rosaria, a sister in Mondstadt's Church of Favonius. A sister of the church, though you wouldn't know it if it weren't for her attire. An unusual woman with sharp, piercing words and a cold manner. Her movements are unpredictable. She often leaves without notifying anyone. She acts with some kind of purpose, but others don't seem to know exactly what she stands for...",
    "region": "Mondstadt",
    "faction": "Church of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Rosaria.webp",
    "quote": "https://impact.moe/assets/img/quotes/rosaria.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Rosaria.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/rosaria.webp",
    "title": "Thorny Benevolence",
    "birthday": "January 24th",
    "constellation": "Spinea Corona",
    "chineseVA": "Anqi Zhang (张安琪)",
    "japaneseVA": "Ai Kakuma (加隈亜衣)",
    "englishVA": "Elizabeth Maxwell",
    "koreanVA": "Kim Bo-na (김보나)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "sara",
    "name": "Kujou Sara",
    "tier": "",
    "rarity": 4,
    "weapon": "Bow",
    "element": "Electro",
    "description":
        "Leader of the Tenryou Commission's forces. A charismatic woman who acts as swiftly as a storm wind and always honors her word. She bears the title of \"Devotee of the Divine\" and has sworn her allegiance to the Raiden Shogun.",
    "region": "Inazuma",
    "faction": "Tenryou Commission",
    "image": "https://impact.moe/assets/img/portraits/Sara.webp",
    "quote": "https://impact.moe/assets/img/quotes/sara.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Sara.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/sara.webp",
    "title": "Crowfeather Kaburaya",
    "birthday": "July 14th",
    "constellation": "Flabellum",
    "chineseVA": "Yang Menglu (杨梦露)",
    "japaneseVA": "Asami Seto (瀬戸麻沙美)",
    "englishVA": "Jeannie Tirado",
    "koreanVA": "Mun Ji-yeong (문지영)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "sayu",
    "name": "Sayu",
    "tier": "A",
    "rarity": 4,
    "weapon": "Claymore",
    "element": "Anemo",
    "description":
        "A pint-sized ninja attached to the Shiyuumatsu-Ban, who always seems sleep-deprived.",
    "region": "Inazuma",
    "faction": "Shiyuumatsu-Ban",
    "image": "https://impact.moe/assets/img/portraits/Sayu.webp",
    "quote": "https://impact.moe/assets/img/quotes/sayu.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Sayu.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/sayu.webp",
    "title": "Mujina Ninja",
    "birthday": "October 19th",
    "constellation": "Nyctereutes Minor",
    "chineseVA": "Sakula (小舞)",
    "japaneseVA": "Aya Suzaki (洲崎綾)",
    "englishVA": "Lilypichu (Lily Ki)",
    "koreanVA": "Lee Ji-hyeon (이지현)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "scaramouche",
    "name": "Scaramouche",
    "tier": "",
    "rarity": 5,
    "weapon": "catalyst",
    "element": "electro",
    "description": "",
    "region": "Snezhnaya",
    "faction": "Fatui",
    "image": "",
    "quote": "",
    "icon": "",
    "squareCard": "",
    "title": "Balladeer",
    "birthday": "",
    "constellation": "",
    "chineseVA": "",
    "japaneseVA": "",
    "englishVA": "",
    "koreanVA": "",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "shenhe",
    "name": "Shenhe",
    "tier": "B",
    "rarity": 5,
    "weapon": "Polearm",
    "element": "Cryo",
    "description":
        "Even though she was born in the human world, she ended up being an adepti disciple. She grew up in the mountains far away from Liyue Harbor, her soul bound with red ropes, training both her body and mind. Despite having the elegant temperament of an adeptus, she seems to be shrouded in mystery.",
    "region": "Liyue",
    "faction": "Liyue Harbor",
    "image": "https://impact.moe/assets/img/portraits/Shenhe.webp",
    "quote": "https://impact.moe/assets/img/quotes/shenhe.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Shenhe.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/Shenhe.webp",
    "title": "Ethereal Soul Amidst the Mortal Realm",
    "birthday": "March 10th",
    "constellation": "Crista Doloris",
    "chineseVA": "Ziyi Qin(秦紫翼)",
    "japaneseVA": "Ayako Kawasumi (川澄綾子)",
    "englishVA": "Chelsea Kwoka",
    "koreanVA": "Lee Hyun-jin (이현진)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "shogun",
    "name": "Raiden Shogun",
    "tier": "",
    "rarity": 5,
    "weapon": "Polearm",
    "element": "Electro",
    "description":
        "The Raiden Shogun is the awesome and terrible power of thunder incarnate, the exalted ruler of the Inazuma Shogunate. With the might of lightning at her disposal, she commits herself to the solitary pursuit of eternity.",
    "region": "Inazuma",
    "faction": "Archon",
    "image": "https://impact.moe/assets/img/portraits/Shogun.webp",
    "quote": "https://impact.moe/assets/img/quotes/shogun.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Shogun.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/shogun.webp",
    "title": "Plane of Euthymia",
    "birthday": "June 26th",
    "constellation": "Imperatrix Umbrosa",
    "chineseVA": "Juhuahua (菊花花)",
    "japaneseVA": "Miyuki Sawashiro (沢城みゆき)",
    "englishVA": "Anne Yatco",
    "koreanVA": "Park Ji-yoon (박지윤)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "sucrose",
    "name": "Sucrose",
    "tier": "B",
    "rarity": 4,
    "weapon": "Catalyst",
    "element": "Anemo",
    "description":
        "An alchemist with an insatiable curiosity towards the world and everything in it. Attached to the Knights of Favonius as an assistant to Albedo, her area of focus is \"bio-alchemy.\" She strives to enrich the world by transforming living things with the power of alchemy.",
    "region": "Mondstadt",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Sucrose.webp",
    "quote": "https://impact.moe/assets/img/quotes/sucrose.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Sucrose.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/sucrose.webp",
    "title": "Harmless Sweetie",
    "birthday": "November 26th",
    "constellation": "Ampulla",
    "chineseVA": "Xiaogan (小敢)",
    "japaneseVA": "Akane Fujita (藤田 茜)",
    "englishVA": "Valeria Rodriguez",
    "koreanVA": "Kim Hayeong (김하영)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "tartaglia",
    "name": "Tartaglia",
    "tier": "S",
    "rarity": 5,
    "weapon": "Bow",
    "element": "Hydro",
    "description":
        "Meet Tartaglia — the cunning Snezhnayan whose unpredictable personality keeps people guessing his every move.",
    "region": "Snezhnaya",
    "faction": "Fatui",
    "image": "https://impact.moe/assets/img/portraits/Tartaglia.webp",
    "quote": "https://impact.moe/assets/img/quotes/tartaglia.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Tartaglia.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/tartaglia.webp",
    "title": "Childe",
    "birthday": "July 20th",
    "constellation": "Monoceros Caeli",
    "chineseVA": "Dong Yu (鱼冻)",
    "japaneseVA": "Ryohei Kimura (木村 良平)",
    "englishVA": "Griffin Burns",
    "koreanVA": "Nam Doh-hyeong (남도형)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "thoma",
    "name": "Thoma",
    "tier": "",
    "rarity": 4,
    "weapon": "Polearm",
    "element": "Pyro",
    "description":
        "Perhaps influenced by the relaxed and happy atmosphere of his hometown, Thoma is very good at socializing. Although he is an outlander, he has built an unexpectedly powerful network of people in Inazuma.",
    "region": "Inazuma",
    "faction": "Kamisato Clan",
    "image": "https://impact.moe/assets/img/portraits/Thoma.webp",
    "quote": "https://impact.moe/assets/img/quotes/thoma.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Thoma.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/thoma.webp",
    "title": "Protector From Afar",
    "birthday": "January 9th",
    "constellation": "Rubeum Scutum",
    "chineseVA": "Pei Zhang (张沛)",
    "japaneseVA": "Masakazu Morita (森田 成一)",
    "englishVA": "Christian Banas",
    "koreanVA": "Ryu Seung-gon (류승곤)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "traveler-anemo",
    "name": "Traveler (Anemo)",
    "tier": "C",
    "rarity": 5,
    "weapon": "Sword",
    "element": "Anemo",
    "description":
        "The Traveler is the protagonist and a playable character in Genshin Impact. At the beginning of the game, both genders are twin siblings from another world, travelling throughout the universe, until an Unknown God ambushed, capturing one of them, and sealed their ways to travel, leaving them stranded on Teyvat.",
    "region": "Mondstadt",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Traveler.webp",
    "quote": "",
    "icon": "https://impact.moe/assets/img/character-icons/Traveler.webp",
    "squareCard":
        "https://impact.moe/assets/img/square-cards/traveler-anemo.webp",
    "title": "Honorary Knight",
    "birthday": "Player's Choice",
    "constellation": "Viator/Viatrix",
    "chineseVA": "Aether: Hailong Dong (董海龙) Lumine: Ning Yan (宴宁)",
    "japaneseVA": "Aether: Shun Horie (堀江 瞬) Lumine: Aoi Yūki (悠木 碧)",
    "englishVA": "Aether: Zach Aguilar Lumine: Sarah Miller-Crews",
    "koreanVA": "Aether: Gyeongtae Lee (이경태) Lumine: Saea Lee (이새아)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "traveler-electro",
    "name": "Traveler (Electro)",
    "tier": "B",
    "rarity": 5,
    "weapon": "Sword",
    "element": "Electro",
    "description":
        "The Traveler is the protagonist and a playable character in Genshin Impact. At the beginning of the game, both genders are twin siblings from another world, travelling throughout the universe, until an Unknown God ambushed, capturing one of them, and sealed their ways to travel, leaving them stranded on Teyvat.",
    "region": "Inazuma",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Traveler.webp",
    "quote": "",
    "icon": "https://impact.moe/assets/img/character-icons/Traveler.webp",
    "squareCard":
        "https://impact.moe/assets/img/square-cards/traveler-electro.webp",
    "title": "Honorary Knight",
    "birthday": "Player's Choice",
    "constellation": "Viator/Viatrix",
    "chineseVA": "Aether: Hailong Dong (董海龙) Lumine: Ning Yan (宴宁)",
    "japaneseVA": "Aether: Shun Horie (堀江 瞬) Lumine: Aoi Yūki (悠木 碧)",
    "englishVA": "Aether: Zach Aguilar Lumine: Sarah Miller-Crews",
    "koreanVA": "Aether: Gyeongtae Lee (이경태) Lumine: Saea Lee (이새아)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "traveler-geo",
    "name": "Traveler (Geo)",
    "tier": "D",
    "rarity": 5,
    "weapon": "Sword",
    "element": "Geo",
    "description":
        "The Traveler is the protagonist and a playable character in Genshin Impact. At the beginning of the game, both genders are twin siblings from another world, travelling throughout the universe, until an Unknown God ambushed, capturing one of them, and sealed their ways to travel, leaving them stranded on Teyvat.",
    "region": "Liyue",
    "faction": "Knights of Favonius",
    "image": "https://impact.moe/assets/img/portraits/Traveler.webp",
    "quote": "",
    "icon": "https://impact.moe/assets/img/character-icons/Traveler.webp",
    "squareCard":
        "https://impact.moe/assets/img/square-cards/traveler-geo.webp",
    "title": "Honorary Knight",
    "birthday": "Player's Choice",
    "constellation": "Viator/Viatrix",
    "chineseVA": "Aether: Hailong Dong (董海龙) Lumine: Ning Yan (宴宁)",
    "japaneseVA": "Aether: Shun Horie (堀江 瞬) Lumine: Aoi Yūki (悠木 碧)",
    "englishVA": "Aether: Zach Aguilar Lumine: Sarah Miller-Crews",
    "koreanVA": "Aether: Gyeongtae Lee (이경태) Lumine: Saea Lee (이새아)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "venti",
    "name": "Venti",
    "tier": "S",
    "rarity": 5,
    "weapon": "Bow",
    "element": "Anemo",
    "description":
        "A bard that seems to have arrived on some unknown wind - sometimes sings songs as old as the hills, and other times sings poems fresh and new. Likes apples and lively places, but is not a fan of cheese or anything sticky. When using his Anemo power to control the wind, it often appears as feathers, as he's fond of that which appears light and breezy.",
    "region": "Mondstadt",
    "faction": "Archon",
    "image": "https://impact.moe/assets/img/portraits/Venti.webp",
    "quote": "https://impact.moe/assets/img/quotes/venti.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Venti.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/venti.webp",
    "title": "Windborne Bard",
    "birthday": "June 16th",
    "constellation": "Carmen Dei",
    "chineseVA": "Miaojiang (喵酱)",
    "japaneseVA": "Ayumu Murase (村瀬 歩)",
    "englishVA": "Erika Harlacher",
    "koreanVA": "Jung Yoo-jung (정유정)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "xiangling",
    "name": "Xiangling",
    "tier": "B",
    "rarity": 4,
    "weapon": "Polearm",
    "element": "Pyro",
    "description":
        "The Head Chef at the Wanmin Restaurant and also a waitress there, Xiangling is extremely passionate about cooking and excels at her signature hot and spicy dishes. Though still young, Xiangling is a true master of the culinary arts with all the skills of a kitchen veteran. She enjoys a good reputation among the hearty eaters at Chihu Rock. There's absolutely no need to be nervous if she wants you to sample her latest creation. It will not disappoint. Promise.",
    "region": "Liyue",
    "faction": "Wanmin Restaurant",
    "image": "https://impact.moe/assets/img/portraits/Xiangling.webp",
    "quote": "https://impact.moe/assets/img/quotes/xiangling.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Xiangling.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/xiangling.webp",
    "title": "Exquisite Delicacy",
    "birthday": "November 2nd",
    "constellation": "Trulla",
    "chineseVA": "Li Jiang (蒋丽)",
    "japaneseVA": "Ari Ozawa (小澤亜李)",
    "englishVA": "Jackie Lastra",
    "koreanVA": "Yoon Ah-yeong (윤아영)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "xiao",
    "name": "Xiao",
    "tier": "S",
    "rarity": 5,
    "weapon": "Polearm",
    "element": "Anemo",
    "description":
        "One of the \"Mighty and Illuminated Adepti\" guarding Liyue, also heralded as the \"Guardian Yaksha\". Despite his appearance as a young man, occasional legends about him have been documented in ancient books. He is especially fond of Wangshu Inn's Almond Tofu. The reason is that the dish tastes just like the \"dreams\" he used to devour.",
    "region": "Liyue",
    "faction": "Liyue Adeptus",
    "image": "https://impact.moe/assets/img/portraits/Xiao.webp",
    "quote": "https://impact.moe/assets/img/quotes/xiao.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Xiao.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/xiao.webp",
    "title": "Vigilant Yaksha",
    "birthday": "April 17th",
    "constellation": "Alatus Nemeseos",
    "chineseVA": "Jinchuan (金船)",
    "japaneseVA": "Yoshitsugu Matsuoka (松岡 禎丞)",
    "englishVA": "Laila Berzins",
    "koreanVA": "Jeong Yoo-Mi (정유미)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "xingqiu",
    "name": "Xingqiu",
    "tier": "A",
    "rarity": 4,
    "weapon": "Sword",
    "element": "Hydro",
    "description":
        "The second son of the Feiyun Commerce Guild, Xingqiu has had a reputation for being studious and polite ever since he was a young child. But there is another side to the mild-mannered Xingqiu everyone knows. A daring, adventurous and much more mischievous side...",
    "region": "Liyue",
    "faction": "Feiyun Commerce Guild",
    "image": "https://impact.moe/assets/img/portraits/Xingqiu.webp",
    "quote": "https://impact.moe/assets/img/quotes/xingqiu.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Xingqiu.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/xingqiu.webp",
    "title": "Juvenile Galant",
    "birthday": "October 9th",
    "constellation": "Fabulae Textile",
    "chineseVA": "Yajing Tang (唐雅菁)",
    "japaneseVA": "Junko Minagawa (皆川 純子)",
    "englishVA": "Cristina Vee Valenzuela",
    "koreanVA": "Kwak Kyumi (곽규미)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "xinyan",
    "name": "Xinyan",
    "tier": "C",
    "rarity": 4,
    "weapon": "Claymore",
    "element": "Pyro",
    "description":
        "Rock 'n' roll is an avant-garde art in Liyue Harbor and Xinyan is the pioneer in this field. She rebels against ossified prejudices, using her music and passionate singing to awaken dazed souls fatigued by worldly matters. If you get the chance, do not miss out on her next performance!",
    "region": "Liyue",
    "faction": "Liyue Harbor",
    "image": "https://impact.moe/assets/img/portraits/Xinyan.webp",
    "quote": "https://impact.moe/assets/img/quotes/xinyan.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Xinyan.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/xinyan.webp",
    "title": "Blazing Riff",
    "birthday": "October 16th",
    "constellation": "Fila Ignium",
    "chineseVA": "Yaxin Wang (王雅欣)",
    "japaneseVA": "Chiaki Takahashi (たかはし 智秋)",
    "englishVA": "Laura Stahl",
    "koreanVA": "Kim Chae-ha (김채하)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "yanfei",
    "name": "Yanfei",
    "tier": "B",
    "rarity": 4,
    "weapon": "Catalyst",
    "element": "Pyro",
    "description":
        "A half-illuminated beast and highly-skilled legal adviser. She combines adherence to the legal codices and reasonable flexibility to find the perfect balance in her work. She devotes herself to protecting the fairness of contracts in Liyue with her identity as a legal adviser and her unique experience and methods.",
    "region": "Liyue",
    "faction": "Liyue Harbor",
    "image": "https://impact.moe/assets/img/portraits/Yanfei.webp",
    "quote": "https://impact.moe/assets/img/quotes/yanfei.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Yanfei.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/yanfei.webp",
    "title": "Wise Innocence",
    "birthday": "July 28th",
    "constellation": "\r\nBestia Iustitia",
    "chineseVA": "Ziwu Su (苏子芜)",
    "japaneseVA": "\r\nYumiri Hanamori (花守 ゆみり)",
    "englishVA": "Lizzie Freeman",
    "koreanVA": "Cho Kyungyi (조경이)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "yaoyao",
    "name": "Yaoyao",
    "tier": "",
    "rarity": 0,
    "weapon": "catalyst",
    "element": "Dendro",
    "description": "",
    "region": "Liyue",
    "faction": "",
    "image": "",
    "quote": "",
    "icon": "",
    "squareCard": "",
    "title": "",
    "birthday": "",
    "constellation": "",
    "chineseVA": "",
    "japaneseVA": "",
    "englishVA": "",
    "koreanVA": "",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "yoimiya",
    "name": "Yoimiya",
    "tier": "C",
    "rarity": 5,
    "weapon": "Bow",
    "element": "Pyro",
    "description":
        "Owner of Naganohara Fireworks, known as \"Queen of the Summer Festival,\" she excels in her craft of creating fireworks that symbolize people's hopes and dreams.",
    "region": "Inazuma",
    "faction": "Naganohara Fireworks",
    "image": "https://impact.moe/assets/img/portraits/Yoimiya.webp",
    "quote": "https://impact.moe/assets/img/quotes/yoimiya.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Yoimiya.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/yoimiya.webp",
    "title": "Frolicking Flames",
    "birthday": "June 21st",
    "constellation": "Carassius Auratus",
    "chineseVA": "Jinna (金娜)",
    "japaneseVA": "Kana Ueda (植田佳奈)",
    "englishVA": "Jenny Yokobori",
    "koreanVA": "Bak Sin-hui (박신희)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "yunjin",
    "name": "Yun Jin",
    "tier": "C",
    "rarity": 4,
    "weapon": "Polearm",
    "element": "Geo",
    "description":
        "The current director of the Yun-Han Opera Troupe, a renowned Liyue opera singer who is skilled in both playwriting and singing. Her style is one-of-a-kind, exquisite and delicate, much like the person herself.",
    "region": "Liyue",
    "faction": "Yun-Han Opera Troupe",
    "image": "https://impact.moe/assets/img/portraits/Yun-Jin.webp",
    "quote": "https://impact.moe/assets/img/quotes/yun-jin.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Yun-Jin.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/yun-jin.webp",
    "title": "Current Director of Yun-Han Opera Troupe",
    "birthday": "May 21st",
    "constellation": "Opera Grandis",
    "chineseVA": "Wenxiao He (贺文潇)",
    "japaneseVA": "Koiwai Kotori (小岩井ことり)",
    "englishVA": "Judy Alice Lee",
    "koreanVA": "Sa Mun-yeong (사문영)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  },
  {
    "id": "zhongli",
    "name": "Zhongli",
    "tier": "A",
    "rarity": 5,
    "weapon": "Polearm",
    "element": "Geo",
    "description":
        "Wangsheng Funeral Parlor's mysterious consultant. Handsome, elegant, and surpassingly learned. Though no one knows where Zhongli is from, he is a master of courtesy and rules. From his seat at Wangsheng Funeral Parlor, he performs all manner of rituals.",
    "region": "Liyue",
    "faction": "Wangsheng Funeral Parlor",
    "image": "https://impact.moe/assets/img/portraits/Zhongli.webp",
    "quote": "https://impact.moe/assets/img/quotes/zhongli.webp",
    "icon": "https://impact.moe/assets/img/character-icons/Zhongli.webp",
    "squareCard": "https://impact.moe/assets/img/square-cards/zhongli.webp",
    "title": "Vago Mundo",
    "birthday": "December 31st",
    "constellation": "Lapid Dei",
    "chineseVA": "Pengbo (彭博)",
    "japaneseVA": "Tomoaki Maeno (前野 智昭)",
    "englishVA": "Keith Silverstein",
    "koreanVA": "Pyo Yeong-jae (표영재)",
    "talents": null,
    "constellations": null,
    "roles": null,
    "characterOverview": null
  }
];
